site_name: AstroPix Documentation
# nav:
#   - .
nav:
  - Getting Started:
    - index.md
  - AstroPix2 User Guide:
    - astropix2/index.md
    - Pins: astropix2/pins.md
  - AstroPix3 User Guide:
    - astropix3/index.md
    - Pixel Electronics: astropix3/pixelelectronics.md
    - Matrix Readout: astropix3/readout.md
    - SPI Interface: astropix3/spi.md
    - DAC: astropix3/dac.md
    - Injection: astropix3/injection.md
    - Configuration Registers: astropix3/configuration.md
    - Pins: astropix3/pins.md
  - AstroPix4 User Guide:
    - astropix4/index.md
  - AstroPix5 User Guide:
    - astropix5/index.md
    - SPI Interface: astropix5/spi.md
    - DAC: astropix5/dac.md
    - Injection: astropix5/injection.md
    - Pins: astropix5/pins.md

docs_dir: docs
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - toc.integrate
  language: en
  logo: ADL_Logo.png
  favicon: ADL_Logo.png
copyright: Nicolas Striebig 2025
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - attr_list
  - abbr
  - md_in_html
  - markdown_include.include:
        base_path: docs
  - pymdownx.arithmatex:
      generic: true
  - toc:
      title: "Table of Contents"
      toc_depth: "2-5"
      permalink: true

plugins:
  - privacy
  - drawio:
      toolbar: true # control if hovering on a diagram shows a toolbar for zooming or not (default: true)
      tooltips: true # control if tooltips will be shown (default: true)
      edit: false # control if edit button will be shown in the lightbox view (default: true)
      border: 10 # increase or decrease the border / margin around your diagrams (default: 5)
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_themed: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - markdownwavedrom
  - include-markdown

# markdown_extensions:
#   - pymdownx.snippets:
#       auto_append:
#         - includes/abbreviations.md

# watch:
#   - includes

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/wavedrom.js
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.1.0/skins/default.js
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.1.0/wavedrom.min.js

  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css